name: Sincronizacion Diaria BCV
on:
  schedule:
    - cron: '25 13 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npx tsx sync-bcv.ts
        env:
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
          HASURA_SECRET: ${{ secrets.HASURA_SECRET }}